# INFO : si tu as déjà lancer un containeur db avec d'anciennes variables d'environnement
# supprime les volumes docker compose down -v (-v = volumes)
# Si ça persiste docker volumes ls (pour afficher les volumes encore existant)
# docker volumes rm nom_du_volume (ex todo_data)

version: "3.9"
services:
  postgresql:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todo_data:/var/lib/postgresql
  
  pgadmin:
    # see https://hub.docker.com/r/dpage/pgadmin4
    image: dpage/pgadmin4:latest # To download the latest image
    volumes:
      - pgadmin_working_dir:/var/lib/pgadmin
      - pgadmin_config_dir:/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${MAIL_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgresql
    ports:
      - "5433:80"
  
  backend:
    # pense à build l'image avant de lancer le compose - pareil pour le front plus tard.
    image: todolist_api:latest
    # je déclarer tout les variables d'env dont j'ai besoin pour mon container
    # ${} permet de récupérer la var d'env
    environment:
      PORT: ${PORT}
      # Dans le cas d'app containeuriser, il faut remplacer localhost par le host docker (le nom du service)
      DB_HOST: postgresql
      # DB_PORT=utiliser le deuxième port de la propriété ports: - "XXXX:XXXX"
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      RESET_PASSWORD_SECRET: ${RESET_PASSWORD_SECRET}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    ports:
      - "3000:3000"
    depends_on:
      - postgresql


volumes:
  todo_data:
    name: todo_data 
  pgadmin_working_dir:
  pgadmin_config_dir: